# Move to ~/Brewfile in order to be able to use `brew bundle --global` command
# Languages (node, rust, go, bun, deno, golangci-lint) are managed via mise, not brew.

tap "buo/cask-upgrade"

brew "bat"
brew "btop"
brew "coreutils"
brew "cspell"
brew "dnsmasq", restart_service: :changed
brew "eza"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gnupg"
brew "grep"
brew "httpie"
brew "jq"
brew "luv"
brew "mkcert"
brew "openssh"
brew "poppler"
brew "ripgrep"
brew "sevenzip"
brew "snzip"
brew "tailscale"
brew "tlrc"
brew "tmux"
brew "tree"
brew "tree-sitter-cli"
brew "yazi"
brew "ykman"
brew "yq"
brew "zoxide"
tap "felixkratz/formulae"
brew "felixkratz/formulae/borders"
tap "tw93/tap"
brew "mole"

# AI
tap "anomalyco/tap"
brew "anomalyco/tap/opencode"
brew "anomalyco/tap/sst"
brew "herdr"
brew "pi-coding-agent"

# Coding
brew "neovim"
brew "git"
brew "git-delta"
brew "git-filter-repo"
brew "gh"
brew "lazydocker"
brew "lazygit"
brew "ast-grep"
brew "worktrunk"
tap "modem-dev/tap"
brew "modem-dev/tap/hunk"

# Version/package managers (languages themselves via mise)
brew "mise"
brew "uv"

# Databases
brew "libpq"
brew "sqlcmd"
brew "supabase"

# AWS
brew "aws-sam-cli"
brew "awscli"

cask "1password-cli"
cask "adobe-acrobat-reader"
cask "arc"
cask "bambu-studio"
cask "boop"
cask "brave-browser"
cask "chatgpt"
cask "claude"
cask "cmux"
cask "codex"
cask "cyberduck"
cask "dbeaver-community"
cask "font-caskaydia-mono-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-monaspace"
cask "ghostty"
cask "google-chrome"
cask "grok-bot"
cask "handbrake-app"
cask "imageoptim"
cask "karabiner-elements"
cask "keka"
cask "leapp"
cask "lulu"
cask "notion"
cask "obsidian"
cask "signal"
cask "steam"
cask "tailscale-app"
cask "telegram"
cask "vlc"
cask "wispr-flow"
cask "yubico-authenticator"
